### ISSUE TITLE
retrieve curated interface annotation

### ISSUE THREAD

**Issue by mgiulini** [haddocking/arctic3d#131]
protein protein interactions are not always present in the pdbe-kb database, but we can retrieve data from the annotations present in the db. For example P21890 does not have any interacting partners (https://www.ebi.ac.uk/pdbe/pdbe-kb/proteins/P21890/interactions), but the interface information is annotated here https://www.ebi.ac.uk/pdbe/graph-api/uniprot/annotations/P21890

This would dramatically increase arctic3d's success rate.

@rvhonorato what do you think?

**Comment by rvhonorato** [comment]
Sounds like a great idea! The annotation keys are `3Dcomplex` we should just dig deeper to confirm that they are coming from [here](https://shmoo.weizmann.ac.il/elevy/3dcomplexV6/About.cgi).
