### ISSUE TITLE
Cluster set of interfaces

### ISSUE THREAD

**Issue by anton-bushuiev** [haddocking/arctic3d#196]
Hi 👋! 

I have a set of .pdb files containing the extracted interfaces of protein--protein interactions. Is it possible to cluster them with ARCTIC-3D? I could not find the answer in [Examples](https://github.com/haddocking/arctic3d/blob/main/docs/examples.md) and the docs. It seems that `arctic3d.modules.cluster_interfaces.cluster_interfaces` may be what I am looking for but I am not sure how to use it.

Thank you!

**Comment by mgiulini** [comment]
Hi @anton-bushuiev , thanks for your interest in ARCTIC-3D!

ARCTIC-3D is designed to cluster protein-specific interfaces (i.e. different interfaces formed by the same protein), so if you have a set of different interfaces belonging to a certain protein you can group them in an `interface_file` (an example is given here https://github.com/haddocking/arctic3d/blob/main/example/1ppe_E_example_interfaces.txt), where each interface is defined by its residues, and then run the following command:
`arctic3d YOUR_PDB --interface_file YOUR_INTERFACE_FILE`

**Comment by anton-bushuiev** [comment]
Ah, I see. Thank you for the clarification. In my case, I have different proteins.

**Comment by mgiulini** [comment]
Then it's probably better to look at some other method!
