### ISSUE TITLE
renumbering haddock pdbs according to uniprot?

### ISSUE THREAD

**Issue by mgiulini** [haddocking/arctic3d#76]
renumbering input pdbs according to a specific uniprot numbering can be quite painful. I wrote a script for that, should we include it in the benchmark? may it be useful in other contexts?

**Comment by rvhonorato** [comment]
I think its quite useful to have the PDBs match the canonical numbering! Goes into the line of input standardization.

**Comment by amjjbonvin** [comment]
Aren’t the mmCIF files now also providing it?

**Comment by mgiulini** [comment]
> Aren’t the mmCIF files now also providing it?

They are indeed, I didn't know it! I guess this could remove arctic3d hard dependency on the pdbrenum web server.
```
1 A 1 7 GLY G G 51 P49137 1 1 ? y 1 CATH 3.30.200.20 2ozaA01 1 1
1 A 2 7 GLY G G 51 P49137 1 1 ? y 1 SCOP2 8031356 SCOP2-FA 1 1
1 A 3 7 GLY G G 51 P49137 1 1 ? y 1 SCOP2 8043734 SCOP2-SF 1 1
1 A 1 8 LEU L L 52 P49137 1 1 ? y 1 CATH 3.30.200.20 2ozaA01 1 1
1 A 2 8 LEU L L 52 P49137 1 1 ? y 1 SCOP2 8031356 SCOP2-FA 1 1
```
There's a lot of information in these updated files!
